### ISSUE TITLE
extend attester docs and link to it from menu

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-docs#3]
Re: [FlowCrypt Attester Documentation](https://flowcrypt.com/docs/content/technical/attester.html)

currently the docs link directly to `flowcrypt.com/attester`

**Comment by tomholub** [comment]
/content/technical/attester.html

**Comment by seisvelas** [comment]
I think the PR should include

* Explanation of what a key server does, how it works, and why we operate one
* How to use the Attester to upload a key, search for a key, update a key, and delete a key
* Menu link

If you agree with those basic starting points I'll get to work. Otherwise let me know what I'm neglecting.

**Comment by tomholub** [comment]
agree!
