### ISSUE TITLE
customer questions they couldn't find in docs

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-docs#52]
1) Are mobile clients self-reliant or somehow connected to the Gmail app? -> stand-alone imap/smtp clients, work completely independently. It would be nice to have a "Gmail App" integration where user would be sent from Gmail app into FlowCrypt when message is encrypted. Will look into it in the future.
2) do chrome/ff extensions work in incognito? -> not supported yet but possibly works in chrome, not yet on firefox
3) are drafts encrypted? how does it work?

**Comment by seisvelas** [comment]
Before I make a PR for this, I ran across a few things related to these questions that I was uncertain about.

>not supported yet but possibly works in chrome, not yet on firefox

In both Firefox and Chrome I was able to send messages, but not open them. The specific error I receive in either case is "Could not load message due to network error. retry". 

It looks like this was solved at some point in the past, based on the discussion in https://github.com/FlowCrypt/flowcrypt-browser/issues/240, so maybe we added something that broke it. Perhaps I should make an issue? 

But as things stand now, to answer the client's question, neither seem to work.

>are drafts encrypted? how does it work?

Yes, you can write a message without sending it and check your drafts and see that it will be there, encrypted. However, this question has a good point behind it. Here is what the send button for the Secure Compose modal says:

![Screenshot_2020-07-04_00-58-44](https://user-images.githubusercontent.com/44826516/86506075-8e16fc00-bd91-11ea-90c0-0a528c08cee9.png)

"Encrypt, Sign, and Send"

This is in a certain sense inaccurate since the message is already encrypted before that button is clicked. Perhaps we could word the button differently.

Another issue: When I open an encrypted draft, it is opened with the normal plain text Gmail editor, not the Secure Compose editor. 

![Screenshot_2020-07-04_01-08-40](https://user-images.githubusercontent.com/44826516/86506221-03cf9780-bd93-11ea-8fd6-f64e6bfbe734.png)

It offers to open the message in Secure Compose, but if I do that I get a fresh, empty Secure Compose window, sans my draft message.

![Screenshot_2020-07-04_01-09-17](https://user-images.githubusercontent.com/44826516/86506232-219cfc80-bd93-11ea-8ae3-e4bf1d4037c1.png)

I can still retrieve the draft message by manually decrypting it, of course, but I think it would be better if that weren't necessary. If you agree I'll make an issue on flowcrypt-browser.

---

Anyway, once these doubts are clarified I'll go ahead and get a PR up!

**Comment by tomholub** [comment]
> This is in a certain sense inaccurate since the message is already encrypted before that button is clicked. Perhaps we could word the button differently.

The way we do it, we discard the draft and then we send a brand new. But I'm open to changes how we communicate.

> It offers to open the message in Secure Compose, but if I do that I get a fresh, empty Secure Compose window, sans my draft message.

That's a new bug, please file it. Thanks!
