### ISSUE TITLE
PGP version

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-docs#71]
A customer asked what PGP version we use. I looked into it myself, and also asked @tomholub, who said we use PGP 4. 

However, I believe this might be mistaken. To explain, here's a mini-overview of PGP version history:

* **PGP 1.0**: Phil Zimmerman's original PGP command line tool (still extant: http://vpsland.superglobalmegacorp.com/old/install/encryption/pgp/unix_pgp10.tar.gz)
* **PGP 2.x**: [RFC 1991](https://tools.ietf.org/html/rfc1991) Created as a standard for software libraries (instead of a single command line tool) by a broad team of international collaborators with Zimmerman's guidance. After this, Zimmerman licenses PGP to Viacrypt, but only gives them rights to use even-numbered release versions. His releases, in turn, must be odd-numbered.
* **PGP 4**: Viacrypt releases their successor to PGP 2. Since they can only use even numbers for releases, they call it PGP 4.
* **PGP 3 & 5**: Unlike PGP 2, which was an exclusively command line program, PGP 3 was designed from the start as a software library. To reduce confusion over how it could be that PGP 3 is the successor to PGP 4, in 1997 PGP 3 was renamed to PGP 5.
* **OpenPGP**: Zimmerman convinces the IETF to create an open standard for PGP, based on PGP 5. This results in a variety of RFC's, chiefly RFC 2440 & RFC 4880
* **OpenPGP.js**: A JavaScript implementation of RFC 4880 (OpenPGP).

In a private convo, @tomholub mentioned v4 in relation to GPG. This makes sense, because when you look at a PGP key with GPG it gives you a 'version'. Example:

```
:public key packet:
	version 4, algo 1, created 1598242096, expires 0
```

However, that version refers to `packet version` (https://tools.ietf.org/html/rfc4880#section-5.5.2) and is not the PGP version (eg, version 3 packets come from PGP 2.x, and version 4 packets come from PGP 5). 

Perhaps I should integrate this information into the docs, somewhere (hopefully more eloquently than I've done here)?

Also, maybe I'm wrong, so let me know in that case too.

**Comment by tomholub** [comment]
Yes, I was referring to packet version.

On https://flowcrypt.com/docs/technical/openpgp-compatibility.html we could simply write that we follow OpenPGP specification as per https://tools.ietf.org/html/rfc4880, which itself is not versioned. And that we support OpenPGP packets up to packet version 4.

**Comment by tomholub** [comment]
This list

_PGP 1.0: Phil Zimmerman's original PGP command line tool (still extant: http://vpsland.superglobalmegacorp.com/old/install/encryption/pgp/unix_pgp10.tar.gz)
PGP 2.x: RFC 1991 Created as a standard for software libraries (instead of a single command line tool) by a broad team of international collaborators with Zimmerman's guidance. After this, Zimmerman licenses PGP to Viacrypt, but only gives them rights to use even-numbered release versions. His releases, in turn, must be odd-numbered.
PGP 4: Viacrypt releases their successor to PGP 2. Since they can only use even numbers for releases, they call it PGP 4.
PGP 3 & 5: Unlike PGP 2, which was an exclusively command line program, PGP 3 was designed from the start as a software library. To reduce confusion over how it could be that PGP 3 is the successor to PGP 4, in 1997 PGP 3 was renamed to PGP 5._

Is a list of implementations which are not relevant to our implementation, the really only relevant thing is the OpenPGP spec and whether we follow it, and exactly which rfc.

**Comment by seisvelas** [comment]
At the bottom of https://flowcrypt.com/docs/technical/openpgp-compatibility.html we acknowledge that '[o]ur software uses OpenPGP.js on all platforms.' Since OpenPGP.js itself documents which RFC's it follows, I think this is good enough. 

If anyone disagrees I'll gladly add a note with the specific RFC's that OpenPGP.js itself purports to follow. Otherwise, I'm closing this :)
