### ISSUE TITLE
debug level - verify doc correctness - FINE vs DEBUG

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-docs#98]
From docs:

![image](https://user-images.githubusercontent.com/6306961/100552173-54cdb400-327d-11eb-9355-9e3fa16b2c95.png)

**Comment by tomholub** [comment]
I feel we have some mismatch between the docs and recommended property file on each service and the actual implementation - confusion between FINE and DEBUG levels. Please do some testing to see if the docs and the implementation matches.

**Comment by bilalashraf123** [comment]
The logging level is "DEBUG" rather than "FINE", but I see very few/no messages logged with the level "DEBUG". Hence our claim to debug complex issues with "DEBUG" log level might not be practically very helpful :)

I suggest we remove this line from docs, untill we have good amount of messages logged to "DEBUG" level.

Currently, we mostly log messages using "INFO" and "ERROR" level. Our default level is set to "INFO" which covers higher log levels as well. I think we are ok with the default log level currently in order to diagnose issues using logging.

Thoughts?

**Comment by tomholub** [comment]
I'm not sure - we ourselves indeed don't log anything with DEBUG, but a lot of the underlying libraries do. Have you tried to run for example the EKM with debug mode? the database library will log a lot (unless I'm wrong - I haven't tried in a while).

I imagine, even on EAP that our authentication library would log a bunch of things when DEBUG enabled?

**Comment by bilalashraf123** [comment]
You are right, when running EKM with log level "DEBUG", then lot of debug log is printed from underlying libraries.

The only change in docs for this issue would be i.e. change level from "FINE" to "DEBUG".

**Other Observation:** 
https://flowcrypt.com/docs/technical/enterprise/configuration/postgresql.html - I suggest "Configuring the PosgreSQL server itself" section first and then DB related properties configurations or mention operations sequence wise related to DB configurations.

On very first look, I was under an impression that when EKM will be started for the first time, It will handle creating database, schema and user etc, but I had to manually create it and then configure in properties file. In short, the docs might need to drive users to sequence wise steps. 

create schema command is not there in the docs.

Thoughts?

**Comment by tomholub** [comment]
I responded to database stuff in #119. For debug, yes - let's fix it in the docs.
